/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package book.catalog.api.app

import book.catalog.api.utilities.StringUtils

import org.apache.commons.text.WordUtils

fun main() {
    val tokens = StringUtils.split(MessageUtils.getMessage())
    val result = StringUtils.join(tokens)
    println(WordUtils.capitalize(result))
}
